<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>CoreSim.Tests</AssemblyName>
    <CoreSimRoot Condition="'$(CoreSimRoot)' == ''">../..</CoreSimRoot>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(CoreSimRoot)/src/CoreSim/CoreSim.csproj" />
  </ItemGroup>
</Project>
